---
- name: Change permissions for wordpress wp_sitedir
  ansible.builtin.file:
    path: "{{ wp_docroot }}/{{ wp_sitedir }}"
    state: directory
    owner: "{{ wp_user }}"
    group: "{{ wp_group }}"
    recurse: true

- name: Get unique salt for wordpress
  ansible.builtin.local_action: command curl https://api.wordpress.org/secret-key/1.1/salt
  register: wp_salt

- name: Copy wordpress template
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wp_docroot }}/{{ wp_sitedir }}/wp-config.php"
    mode: "644"
