---
galaxy_info:
  author: Jessica Moreno
  description: NginX Web Server role
  company: Self
  license: NA
  min_ansible_version: "1.4"
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - database
    - sql
dependencies:
  - {role: common}
