---
# www.yml : playbook for web servers
- name: Webserver playbook
  hosts: webtarget
    # remote_users: osboxes
  become: true
  pre_tasks:
    - name: "Output beginning..."
      ansible.builtin.debug:
        msg: echo 'I":" Beginning to configure the web server...'
  roles:
    - { role: nginx, when: ansible_os_family == 'Debian'}
    - php5-fpm
    - wordpress
  post_tasks:
    - name: "Output end"
      ansible.builtin.debug:
        msg: echo 'I":" Done configuring nginx web server...'
